### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by shaps80** [AvdLee/AppUpdately#1]
Hey love this thanks for making it.

Just wondering if you've encountered this at all: https://github.com/mas-cli/mas/issues/336

I want to use your library for an app that's only iOS so won't affect me personally but as I'd seen it thought I'd mention it just in case.

Thanks again!

**Comment by AvdLee** [comment]
@shaps80 I did not encounter such, but I do know that the JSON can be updated quicker than the App Store in some cases. I might build a 24 hours delay before notifying about an update to encounter for this

**Comment by shaps80** [comment]
Right makes sense. In some cases the user's app may even auto-update in that time. Nice one, thanks for coming back to me 👍🏻
